/*
=========================================
Create Database and Schemas
=========================================

Script Purpose:
	This script creates a new database named 'DataWareHouse'. Also, sets up three schemas within the database: 'bronze', 'silver', 'gold'

*/

USE [master]
GO

/****** Object:  Database [DataWareHouse]    Script Date: 28/03/2026 3:00:36 ******/
CREATE DATABASE [DataWareHouse]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataWareHouse', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\DataWareHouse.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DataWareHouse_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\DataWareHouse_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataWareHouse].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataWareHouse] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataWareHouse] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataWareHouse] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataWareHouse] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataWareHouse] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataWareHouse] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DataWareHouse] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataWareHouse] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataWareHouse] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataWareHouse] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataWareHouse] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataWareHouse] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataWareHouse] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataWareHouse] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataWareHouse] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DataWareHouse] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataWareHouse] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataWareHouse] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataWareHouse] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataWareHouse] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataWareHouse] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataWareHouse] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataWareHouse] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataWareHouse] SET  MULTI_USER 
GO

ALTER DATABASE [DataWareHouse] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataWareHouse] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataWareHouse] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataWareHouse] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DataWareHouse] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataWareHouse] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DataWareHouse] SET QUERY_STORE = ON
GO

ALTER DATABASE [DataWareHouse] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DataWareHouse] SET  READ_WRITE 
GO

/*Schema Creation*/

USE [DataWareHouse]
GO

/****** Object:  Schema [bronze]    Script Date: 28/03/2026 3:02:01 ******/
CREATE SCHEMA [bronze]
GO

/****** Object:  Schema [silver]    Script Date: 28/03/2026 3:06:33 ******/
CREATE SCHEMA [silver]
GO

/****** Object:  Schema [gold]    Script Date: 28/03/2026 3:06:55 ******/
CREATE SCHEMA [gold]
GO